apiVersion: v1
kind: Pod
metadata:
  name: welcome-presync-pod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - |
      echo "Pre deployment tasks"
      sleep 10
    image: registry.access.redhat.com/ubi8/ubi:latest
    imagePullPolicy: IfNotPresent
    name: welcome-sleep-pod
  dnsPolicy: ClusterFirst
  restartPolicy: Never
