---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lama
  name: lama
  namespace: lama
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lama
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lama
    spec:
      containers:
      - image: nawang81/lama_k8s:latest
        name: lama
        env:
        - name: COLOR
          value: "green"
        resources: {}
---
