---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lama
spec:
  rules:
    - host: lama.devnation
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lama-service
                port:
                  number: 8080
    - host: lamadai.devnation
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lamadai-service
                port:
                  number: 8080
          - path: "/lamadai"
            pathType: Prefix
            backend:
              service:
                name: lamadai2-service
                port:
                  number: 8080
---