---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lama
  name: lama
  namespace: lama
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lama
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lama
    spec:
      containers:
      - image: nawang81/lama_k8s:latest
        name: lama
        env:
        - name: COLOR
          value: "green"
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lama
  name: lama-service
  namespace: lama
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lama
---

